

const SEED_ARTWORKS = [
  {
    _id: 'a1',
    title: 'Sacred Lotus — Dawn',
    artist: 'Priya Sharma',
    artistId: 'art1',
    category: 'madhubani',
    price: 18000,
    medium: 'Natural pigments on handmade paper',
    dimensions: '24" × 18"',
    description: 'A traditional Madhubani depiction of the sacred lotus in bloom at dawn, using natural earth pigments sourced from Bihar. Each line is drawn freehand using a bamboo stick.',
    image: 'https://images.unsplash.com/photo-1753807005653-81c46cdec6d6?q=80&w=780',
    likes: 124,
    year: 2024,
    sold: false,
    featured: true
  },
  {
    _id: 'a2',
    title: 'Geometric Sunrise',
    artist: 'Rajan Patel',
    artistId: 'art2',
    category: 'warli',
    price: 12500,
    medium: 'White paint on terracotta',
    dimensions: '20" × 20"',
    description: 'Inspired by tribal Warli paintings from Maharashtra, depicting the harvest festival with characteristic geometric human figures and nature motifs.',
    image: 'https://images.unsplash.com/photo-1594814491930-1a857ab5e852?w=600',
    likes: 89,
    year: 2024,
    sold: false,
    featured: false
  },
  {
    _id: 'a3',
    title: 'Portrait in Shadows',
    artist: 'Ananya Krishnan',
    artistId: 'art3',
    category: 'charcoal',
    price: 8500,
    medium: 'Charcoal on 200gsm cartridge paper',
    dimensions: '16" × 20"',
    description: 'A deeply textured charcoal study of a woman in contemplation, exploring the interplay of light and shadow in hyperrealistic portraiture.',
    image: 'https://images.unsplash.com/photo-1598785492268-4847ca9f6955?q=80&w=735',
    likes: 211,
    year: 2023,
    sold: false,
    featured: true
  },
  {
    _id: 'a4',
    title: 'Golden Temple Study',
    artist: 'Vikram Singh',
    artistId: 'art4',
    category: 'graphite',
    price: 6000,
    medium: '6B-2H Graphite on Bristol board',
    dimensions: '12" × 16"',
    description: 'A meticulous graphite architectural study of the Golden Temple at Amritsar, rendered with extraordinary detail in the academic tradition.',
    image: 'https://media.istockphoto.com/id/958941438/photo/big-crowd-visiting-the-golden-temple-in-amritsar-india.jpg?s=1024x1024&w=is&k=20&c=H9Fy5w4PYTHHU4IP76bP7hvv246P7Bg2L4OV0732KxM=',
    likes: 156,
    year: 2024,
    sold: false,
    featured: false
  },
  {
    _id: 'a5',
    title: 'Monsoon Melody',
    artist: 'Priya Sharma',
    artistId: 'art1',
    category: 'acrylic',
    price: 22000,
    medium: 'Acrylic on stretched canvas',
    dimensions: '30" × 40"',
    description: 'An expressive acrylic capturing the first monsoon shower over a rural Indian landscape, with bold impasto brushwork conveying movement and emotion.',
    image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=600&q=80',
    likes: 198,
    year: 2024,
    sold: false,
    featured: true
  },
  {
    _id: 'a6',
    title: 'Tanjore Krishna',
    artist: 'Meera Iyer',
    artistId: 'art5',
    category: 'tanjore',
    price: 45000,
    medium: 'Gold foil & gemstones on wooden panel',
    dimensions: '18" × 24"',
    description: 'A classical Tanjore painting of Lord Krishna in the traditional style, featuring genuine 22-karat gold foil, semi-precious stone embellishments, and vibrant pigments.',
    image: 'https://images.unsplash.com/photo-1580136579312-94651dfd596d?w=600&q=80',
    likes: 342,
    year: 2023,
    sold: false,
    featured: true
  },
  {
    _id: 'a7',
    title: 'Deccan Journey',
    artist: 'Arjun Mehta',
    artistId: 'art6',
    category: 'miniature',
    price: 35000,
    medium: 'Natural pigments & 24K gold on vellum',
    dimensions: '8" × 10"',
    description: 'A miniature painting in the Deccani school tradition, depicting a royal procession with extraordinary fine detail, requiring over 200 hours of work.',
    image: 'https://images.unsplash.com/photo-1547891654-e66ed7ebb968?w=600&q=80',
    likes: 267,
    year: 2024,
    sold: false,
    featured: false
  },
  {
    _id: 'a8',
    title: 'Ocean of Thought',
    artist: 'Ananya Krishnan',
    artistId: 'art3',
    category: 'oil',
    price: 55000,
    medium: 'Oil on linen canvas',
    dimensions: '36" × 48"',
    description: 'A large-scale oil painting in the tradition of Indian Impressionism, capturing a contemplative seascape with visible, energetic brushwork and extraordinary color depth.',
    image: 'https://images.unsplash.com/photo-1531913764164-f85c52e6e654?w=600&q=80',
    likes: 389,
    year: 2024,
    sold: false,
    featured: true
  },
  {
    _id: 'a9',
    title: 'Pattachitra Vishnu',
    artist: 'Suresh Das',
    artistId: 'art7',
    category: 'pattachitra',
    price: 28000,
    medium: 'Natural colours on cloth-layered canvas',
    dimensions: '22" × 30"',
    description: 'An authentic Odisha Pattachitra depicting Lord Vishnu with the ten avatars, hand-prepared with tamarind paste base and natural stone pigments in the traditional Raghurajpur village style.',
    image: 'https://plus.unsplash.com/premium_photo-1678257846725-e88b5280900b?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cGF0dGFjaGl0cmElMjBwYWludGluZ3xlbnwwfHwwfHx8MA%3D%3D',
    likes: 178,
    year: 2023,
    sold: false,
    featured: false
  },
  {
    _id: 'a10',
    title: 'Neon Durga',
    artist: 'Zara Ahmed',
    artistId: 'art8',
    category: 'digital',
    price: 5000,
    medium: 'Digital illustration, limited print edition',
    dimensions: 'Digital + 24" × 32" Print',
    description: 'A contemporary digital artwork reimagining Goddess Durga in a cyberpunk aesthetic — traditional iconography meets neon hyperrealism. Includes signed print.',
    image: 'https://images.unsplash.com/photo-1640281627204-048abaa465e4?q=80&w=1077&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    likes: 512,
    year: 2024,
    sold: false,
    featured: true
  },
  {
    _id: 'a11',
    title: 'River Ganga Study',
    artist: 'Vikram Singh',
    artistId: 'art4',
    category: 'graphite',
    price: 7500,
    medium: 'Mechanical pencil & graphite on vellum',
    dimensions: '18" × 24"',
    description: 'An exquisitely detailed graphite panorama of the Ganga ghats at Varanasi, capturing hundreds of individual figures in a single breathtaking composition.',
    image: 'https://media.istockphoto.com/id/515745258/photo/watercolor-maharishi-mahesh-yogi-ashram.webp?a=1&b=1&s=612x612&w=0&k=20&c=Pu5kl1KQdV1RJJ_aAsf8TVqMoZlJs5KlYYZf6ZX-7uc=',
    likes: 143,
    year: 2023,
    sold: true,
    featured: false
  },
  {
    _id: 'a12',
    title: 'Sunset Over Rajasthan',
    artist: 'Rajan Patel',
    artistId: 'art2',
    category: 'oil',
    price: 38000,
    medium: 'Oil on canvas',
    dimensions: '28" × 36"',
    description: 'A luminous oil painting of the Thar Desert at golden hour, painted en plein air during a residency in Jaisalmer. The sky contains over 40 distinct colour layers.',
    image: 'https://media.istockphoto.com/id/467159393/photo/view-of-jodhpur-india-blue-city-buildings-from-surrounding-hills.webp?a=1&b=1&s=612x612&w=0&k=20&c=rlezSel32mNFUV7pHqlbqkHqXViVOHDeALyFUfgn7lk=',
    likes: 221,
    year: 2024,
    sold: false,
    featured: false
  }
];

const SEED_ARTISTS = [
  { _id: 'art1', name: 'Rajat pharswan',   specialty: 'Charcoal & Acrylic', location: 'Dehradun, Uttarakhand', artworks: 12, sales: 34, avatar: 'RS' },
  { _id: 'art2', name: 'Rajan Patel',    specialty: 'Warli & Oil',         location: 'Nashik, MH',        artworks: 8,  sales: 19, avatar: 'RP' },
  { _id: 'art3', name: 'Ananya Krishnan',specialty: 'Charcoal & Oil',      location: 'Chennai, TN',       artworks: 15, sales: 41, avatar: 'AK' },
  { _id: 'art4', name: 'Vikram Singh',   specialty: 'Graphite',            location: 'Varanasi, UP',      artworks: 9,  sales: 22, avatar: 'VS' },
  { _id: 'art5', name: 'Meera Iyer',     specialty: 'Tanjore',             location: 'Thanjavur, TN',     artworks: 6,  sales: 17, avatar: 'MI' },
  { _id: 'art6', name: 'Arjun Mehta',    specialty: 'Miniature',           location: 'Jaipur, RJ',        artworks: 11, sales: 28, avatar: 'AM' },
  { _id: 'art7', name: 'Suresh Das',     specialty: 'Pattachitra',         location: 'Raghurajpur, OD',   artworks: 7,  sales: 15, avatar: 'SD' },
  { _id: 'art8', name: 'Zara Ahmed',     specialty: 'Digital Art',         location: 'Bengaluru, KA',     artworks: 20, sales: 67, avatar: 'ZA' }
];

// Expose globally
window.SEED_ARTWORKS = SEED_ARTWORKS;
window.SEED_ARTISTS  = SEED_ARTISTS;
